---
title: "Procedures for Demo Day"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

These are the procedures we follow on "Demo Day" --- the last class of the course --- during which students present their final projects to an audience of their peers and guests. Demo Day is public. All are welcome.

The only material you need for your presentation is a browser which can show both your project's webpage and your Github repo. We don't use Powerpoint or other nonsense. 

Basic idea is that all students are in two groups: A and B. A presents first. Each breakout room includes two students, an A and a B. (We will post the assignments.)

At the start, we are all in the main room. I offer introductions. I open the breakout rooms. You move yourself to your assigned room. (Guests will also go to the room featuring the student they want to listen to.) Chat politely. I will then issue a Breakout Room message saying to start. The A student presents her work for 4 minutes. The B student asks a lot of questions. So do the guests. These questions often involve your code. You can answer them by showing the actual R code in your Github repo.

After three and a half minutes, I send a Message saying: 30 seconds left. At four minutes, I Message "Switch Rooms!"

Please switch rooms when I ask you to!

Student A stays in the room. Student B moves one room up. From room 6 to room 7, for example. (If you are the B student in the highest room, you move to room 1.) Then, Student A presents again.

After 40 minutes of this, the A students will have presented 7 or 8 times. Good stuff! I bring back everyone to the main room. Say a few words. And then we do the whole thing again, but with the B students presenting and staying put in the rooms. And now the A students move from room to room.

After the B students present, I close the breakout rooms, thereby bringing everyone back together. I offer thanks and congratulations. The course is now complete.
