---
title: "Schedule"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Classes run from 8:00 to 9:00 PM EDT.

Two key resources: [*Preceptor's Primer for Bayesian Data Science*](https://ppbds.github.io/primer/) and its [associated tutorials](https://ppbds.github.io/primer.tutorials/). Assignments associated with a specific lecture must be completed before that lecture.

Completed tutorials are sent to kanes.datacamp@gmail.com with your name and the name of the tutorial separated by a semi-colon  --- like "Sarah Jones; Getting Started" --- in the subject line. If you do not complete the tutorials on time, you will be removed from the class. Send in your tutorial answers saved in *rds* format. If you want to save a copy for your own records, use *html*. 

# Week 1: Visualization

<!-- Visualization - Basic Plots: 82.31 -->
<!-- Visualization - Tidyverse: 110.00 -->
<!-- Visualization - Advanced Plotting: 101.39 -->
<!-- Visualization - Case Studies: 89.26 -->

Looking at the data is the first step in data science.

## Monday July 25

* Read [Getting Started](https://ppbds.github.io/primer/getting-started.html) and follow all the associated instructions. We will do the Getting Started tutorial together in class.

## Wednesday July 27

* Read [Chapter 1 Visualization](https://ppbds.github.io/primer/visualization.html). 

* Complete the two Visualization tutorials: Basic Plots and Tidyverse.

<!-- Make this reading unnesccary by including material in tutorial. -->

* Read [How to use Rpubs](https://ppbds.github.io/primer/tools.html#how-to-use-rpubs). 

* Complete the RStudio and Code tutorial.

## Thursday July 28

* Complete the two Visualization tutorials: Advanced Plotting and Case Studies.

* Complete R Studio and Github tutorial.

Reminder: All work must be completed before class. Failure to submit your tutorial answers will result in you being removed from the course. It is not fair to your fellow students, with whom you will be working in small groups, for you to not be prepared for class.

* **Optional:** Read and watch the videos from [Getting Used to R, RStudio, and R Markdown](https://ismayc.github.io/rbasics-book/) by Chester Ismay and Patrick C. Kennedy

# Week 2: Wrangling

Now that we know how to visualize data that is already clean, we need to learn how to clean up data which might come to us quite messy. To help generate ideas for the final projects, we will also take a close look at US census data.

<!-- Terminal: 90.57 -->
<!-- Wrangling - Overview: 82.00 -->
<!-- Wrangling - Plots: 70.00 -->
<!-- Wrangling - More Plots: 145.62 -->
<!-- Getting Help: 62.12 -->

## Monday August 1

* Complete Terminal tutorial.

* Read [Chapter 2 Wrangling Data](https://ppbds.github.io/primer/wrangling.html). 

* Complete two Wrangling tutorials: Overview and Plots.

## Wednesday August 3

<!-- Make this reading unnecessary. -->
* Read "How to Get Help" from the Appendix on [Tools](https://ppbds.github.io/primer/tools.html). 

* Complete Getting Help tutorial.

* Complete Wrangling - More Plots tutorial.

## Thursday August 4

* Read [Maps](https://ppbds.github.io/primer/maps.html) and [IPUMS](https://ppbds.github.io/primer/ipums.html).

* Complete Downloading Census Data and Mapping tutorials.

* **Optional:** [RStudio Essentials Videos](https://resources.rstudio.com/wistia-rstudio-essentials-2). Most relevant for us are [“Writing code in RStudio”](https://www.rstudio.com/resources/webinars/), [“Projects in RStudio”](https://www.rstudio.com/resources/webinars/) and [“Github and RStudio”](https://www.rstudio.com/resources/webinars/). Again, these are optional! But they are very useful for students who find traditional lectures to be a helpful supplement to classroom practice. The Workflow tutorial is also optional.


# Week 3: Data

Now that we know how to clean and organize messy data, we need to learn how to get some.

<!-- Data Files: 69.69 -->
<!-- Data API: 108.92 -->
<!-- Data Webscraping: 84.83 -->

<!-- Distill: 114.86 -->

## Monday August 8

* Read [Chapter 3 Data](https://ppbds.github.io/primer/data.html). 

* Read the [Style Guide](https://ppbds.github.io/primer/tools.html#style-guide). 

* Complete Data - Files and  Distill tutorial. .


## Wednesday August 10

* Complete Data - AP tutorial.

* Determine the data source you will use for your final project. Don't come to class without one!


## Thursday August 11

* Complete Data - Webscraping tutorial.


# Week 4: Projects


The last week will consist of projects that the students will make. Do you love soccer or wine or NYC politics? The final project provides you with an opportunity to study that topic in depth. Your final project will be, for most of you, the first item in your professional portfolio, something so impressive that you will be eager to show it to graduate schools or potential employers.


## Monday August 15

* You must have a draft of your final project ready to go, including a Distill website and your four sentence introduction. 

* Complete Final Project tutorial before class, or you will not be removed the course. There are no extensions for this assignment.

## Wednesday August 17

* Practice presentations and feedback. You must have your presentation ready to go! 

## Thursday August 18

* Final project presentations. You must invite either your parents or someone else in your family.

* **Optional:** [Distill for R Markdown](https://rstudio.github.io/distill/) is the main documentation page. Key sections are [Creating a Website](https://rstudio.github.io/distill/website.html) and [Publishing Websites](https://rstudio.github.io/distill/publish_website.html). 




<!-- RStudio and Friends: 135.73 -->





