---
title: "Testimonials"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

This course is an excellent introduction to data science for students of any level, with a detailed textbook you can easily follow-along with! --- Stephanie, Senior, White Oaks Secondary School

The data science course was an invaluable experience that provided me with the building blocks to pursue future data science investigations and analyses. The course was well-structured and taught me the fundamentals of not only producing stunning visualizations in R, but most importantly how to think like a data scientist and manage your code effectively. If you are someone interested in dipping their toes in an emerging field of data science, this course will guide you well! --- Dhruv Syngol, Junior, Metea Valley High School

The learning environment was exceptional and encouraged me to navigate the basic challenges of RStudio with other students! It's extremely effective for beginner individuals like me to gain this exposure! - Joyce Li, Senior, White Oaks Secondary School 

The final project allowed me to draw from real world data about mental health disorders and learn how to make conclusions, moving me to be captivated by the data science field. —-- Isaac Frank, Senior, Dublin Coffman High School

This course was really helpful! I learned a lot about data science and how to code in R. My favorite part were the breakout rooms since it allowed for students to share ideas and solve problems together.  --- Gabriel You (dengxuanjia@gmail.com), Senior, White Oaks Secondary School

The course tutorials were very informative and included an abundance of practice to ensure the material was understood. --- Daniel Chen (danielc20051218@gmail.com), Junior, Naperville North High School

The course was an interesting way to learn the basics of data science, with the Final Projects being a great way to show what we grasped. --- Oliver Raif Altindag (oliveraltindag@icloud.com), Freshman, Newton North High School

Great course overall. Introduces data science really well to people who may not have much knowledge about the field by showing important subjects such as data manipulation and visualization. Although some of the course content was slightly repetitive, it was still extremely effective in teaching students both basic and complex topics through the use of peer collaboration and the projects created at the end of the course. Definitely recommend it to anyone who wants an introduction to the language R and data science. --- Abhay Paidipalli (abhay.paidipalli@gmail.com), Junior, James B. Conant High School

Being able to take part of a Harvard course, first of all, is such a valuable experience as you're able to get a feel of the methodology that these elite institutions use. David Kane's Data Science Boot camp was one of the most influential camps I've ever attended. Before this summer, I've never learned or touched a single piece of code and had no interest in programming, but after taking this course, it's really made me fascinated in computer science, even going as far as planning to minor in cs. Working with Preceptor during the camp and under an apprenticeship really helped me gain valuable experience as well as sharpening skills in coding, critical thinking, and discipline. Also, it's completely free. There's so much to gain from this experience and nothing to lose. This camp is definitely one of the best offered to High school students and not one that you should pass on. --- Bryan Li (libryan261@gmail.com/ 614-316-1061), Senior, Dublin Coffman High School

This course was valuable in helping me manage my time during school. Although I did not have any previous experience in R and Rstudio I had to learn to balance my school work and extracurriculars while meeting the demands of the course. --- Joseph Jeiwan Kim (josephjwkim04@gmail.com), Senior, White Oaks High School

This course does a fantastic job of not only putting you in the shoes of a student, learning the underlying coding and statistics, but also putting you in the shoes of a worker, doing real Data Science as a real Data Scientist. --- George, senior, White Oaks Secondary School




