---
title: "Adult Height in the US"
author: "David Kane"
date: "2022-07-27"
output: html_document
---

<!-- Code for Day 2. Assumes students have done the RStudio and Code tutorial. We allow them to make any plot they want. Does not have to be this one. (Indeed, overlapping densities would probably be better.) Anything "interesting" which looks at US heights. Also want to end the class by putting the image up on Rpubs and cleaning it up, by, for example, removing everything from the YAML except the "output: html_document". They should have learned about code chunk options (but probably not enough). Important to highlight the need for code comments and figure labs. -->

<!-- Need a better listing of possible plots, more closely connected to what was actually taught in the tutorials. -->


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(primer.data)
```

```{r, warning=FALSE}
# We should always have as many lines of comments as we have lines of code. Your
# comments are like diary entries. What did you do? Why did you do it? How might
# you do it differently next time? If someone else takes over this project, what
# should they be aware of? If you come back to this project in 6 months, what
# will future-you have forgotten? 

# The better your comments, the more that your collaborators (include
# future-you!) will appreciate working with you.

nhanes |> 
  filter(age >= 18) |> 
  ggplot(data = nhanes, 
         mapping = aes(x = height)) +
    geom_histogram(bins = 30,
                   color = "black",
                   fill = "red") +
    labs(title = "Height of US Adults",
         subtitle = "Men are taller than women, but there is overlap in the distributions",
         x = "Height (cm)",
         y = "Number of people",
         caption = "Data collected from the National Health and Nutrition Examination Survey") +
    facet_wrap(~gender, nrow = 2)
```




